ControlFocus("Open","","Edit1")
Sleep(3000)
ControlSetText("Open","","Edit1","C:\Users\ahmed.mohamed\eclipse-workspace\POC.seleniumWithJava\Needed Files\Infusion_Demo.gre")
Sleep(3000)
ControlClick("Open","","Button1")
